name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5
    steps:
      - uses: wyvox/action@v1
      - run: pnpm lint


  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: wyvox/action@v1
      - run: pnpm test

